import type { Metadata } from "next";
import "@/common/styles/global.scss";
import "animate.css";
import "react-toastify/dist/ReactToastify.css";
import Layout from "@/common/layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Layout>{children}</Layout>
    </html>
  );
}
